# Generated by Django 4.1.2 on 2022-10-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robochat',
            name='ct_id',
        ),
        migrations.AddField(
            model_name='robochat',
            name='senderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msgSender', to='robo.robochat_thread'),
        ),
        migrations.AddField(
            model_name='robochat',
            name='threadId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='robo.robochat_thread'),
        ),
    ]
