# Generated by Django 4.1.2 on 2022-12-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0002_remove_robochat_ct_id_robochat_senderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robochat',
            name='chat',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='robochat',
            name='chatTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
