# Generated by Django 4.1.2 on 2022-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo', '0003_alter_robochat_chat_alter_robochat_chattime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robochat',
            old_name='chat',
            new_name='robo_chat',
        ),
        migrations.RemoveField(
            model_name='robochat',
            name='senderId',
        ),
        migrations.RemoveField(
            model_name='robochat_thread',
            name='r_id',
        ),
        migrations.AddField(
            model_name='robochat',
            name='user_chat',
            field=models.TextField(default=None, max_length=10000000),
        ),
        migrations.DeleteModel(
            name='RoboFriend',
        ),
    ]
