# Generated by Django 4.1.2 on 2022-10-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendschat_thread',
            name='a_f_uid',
        ),
        migrations.RemoveField(
            model_name='friendschat_thread',
            name='b_f_uid',
        ),
    ]
