# Generated by Django 4.1.2 on 2022-10-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_remove_friendschat_thread_a_f_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendschat_thread',
            name='threadId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thread', to='fuser.friendswith'),
        ),
    ]
