# Generated by Django 4.1.2 on 2022-12-07 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuser', '0004_alter_friendschat_thread_fchat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendswith',
            name='a_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='b_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.png', null=True, upload_to='picture'),
        ),
    ]
